name: Trigger Deployment
run-name: ${{ github.sha }}

on:
  push:
    branches:
      - main

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deployment repo
        run: |
          curl --location 'https://api.github.com/repos/madhan-kumar-revature/deployment/dispatches' \
            --header 'Accept: application/vnd.github.v3+json' \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Bearer ${{ secrets.PAT_TOKEN }}' \
            --data '{
              "event_type": "deploy",
              "client_payload": {
                "app_name": "${{ github.event.repository.name }}",
                "commit_sha": "${{ github.sha }}",
                "environment" : "dev"
              }
            }'
